apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-cloud-build
  namespace: argocd
  
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # Add cascade delete behaviour (deletes both the app and its resources, rather than only the app.)

spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true
    #   selfHeal: true
      
  source:
    # Should point to the Spring repo you're going to observe
    repoURL: ${GITHUB_REPO}/argo-deploy-applications-build.git
    targetRevision: main
    path: argo-apps/overlays/local
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: ${ENV}
        - name: DNS_DOMAIN
          value: ${DNS_DOMAIN}
        - name: DNS_ENV
          value: ${DNS_ENV}
        - name: GITHUB_REPO
          value: ${GITHUB_REPO}
        - name: GITHUB_ACCESS_ARGO
          value: ${GITHUB_ACCESS_ARGO}
        - name: GITHUB_ACCESS_ARGO_EVENTS
          value: ${GITHUB_ACCESS_ARGO_EVENTS}
        - name: DEPLOY_KEY_ARGOCD
          value: ${DEPLOY_KEY_ARGOCD}
        - name: DEPLOY_KEY_ARGO
          value: ${DEPLOY_KEY_ARGO}
        - name: SOURCE_KEY_ARGO
          value: ${SOURCE_KEY_ARGO}

          
  destination:
    server: https://kubernetes.default.svc
    namespace: build